Added HTTP get and post request function
sirjoehighton/GodotToolkit pull request #2
Opened 2024-09-22 10:38 UTC by YaikaRace

I added the HTTP get and post functions to make it easier for developers to make HTTP requests, this allows developers to use just one line of code to make a request with the get and post method and receive the response as a dictionary

2024-09-22 14:03 UTC, sirjoehighton requested changes
Add Error Handling besides that looks good to me and ready to Squash and Merge

2024-09-23 03:51 UTC, YaikaRace commented
I already made the changes, I hope you can review it

2024-09-23 05:50 UTC, sirjoehighton requested changes

2024-09-23 05:50 UTC, sirjoehighton commented on addons/godottoolkit/toolkit.gd
> +		printerr("[GodotToolkit] HTTPRequest URL Error: URL can't be empty")
Duplicate Error Print

2024-09-23 05:50 UTC, sirjoehighton commented on addons/godottoolkit/toolkit.gd
> +		printerr("[GodotToolkit] HTTPRequest URL Error: URL can't be empty")
Remove [GodotToolkit]

2024-09-23 05:50 UTC, sirjoehighton commented on addons/godottoolkit/toolkit.gd
> +		var result_msg = "[GodotToolkit] HTTPRequest %s: %s" % [result_lookup.name, result_lookup.description]
Remove [GodotToolkit]

2024-09-23 05:50 UTC, sirjoehighton commented on addons/godottoolkit/toolkit.gd
> +		var error_msg = "[GodotToolkit] HTTPRequest %s: %s" % [error.name, error.description]
Remove [GodotToolkit]

2024-09-23 05:50 UTC, sirjoehighton commented on addons/godottoolkit/toolkit.gd
> +		var error_msg = "[GodotToolkit] HTTPRequest %s: %s" % [error.name, error.description]
Remove [GodotToolkit]

2024-09-23 05:50 UTC, sirjoehighton commented on addons/godottoolkit/toolkit.gd
> +		var result_msg = "[GodotToolkit] HTTPRequest %s: %s" % [result_lookup.name, result_lookup.description]
Remove [GodotToolkit]

2024-09-23 06:18 UTC, YaikaRace commented
Done, I apologize, it's my first pull request

2024-09-25 19:17 UTC, sirjoehighton commented
Awesome, thanks for making the nesscarry changes. Before i merge it have you tested it to make sure it works as intended?

2024-09-25 19:42 UTC, YaikaRace commented
Yes I did tests, and in the tests everything worked correctly

2024-09-27 11:58 UTC, merged